# --------------------------------------------------
#       Определение переменных
# --------------------------------------------------
# Эта переменная автоматически подставит значение SECRET_TOKEN из вашего .env файла
@authToken = {{$dotenv SECRET_TOKEN}}


### --------------------------------------------------
# Запрос №1: Получение рыночных данных
# --------------------------------------------------
POST http://127.0.0.1:8000/get-market-data
Content-Type: application/json

{
    "timeframe": "4h"
}


### --------------------------------------------------
# Запрос №2: Проверка состояния сервера
# --------------------------------------------------
GET http://127.0.0.1:8000/health


### --------------------------------------------------
# Запрос №3: Получение логов
# --------------------------------------------------
GET http://127.0.0.1:8000/logs

Authorization: Bearer {{authToken}}

 
### --------------------------------------------------
# Запрос №4: Очистка логов
# Токен также подставляется автоматически.
# --------------------------------------------------
POST http://127.0.0.1:8000/clear-logs

Authorization: Bearer {{authToken}}

